syntax = "proto3";

package com.example.banksystem;

option java_multiple_files = true;
option java_package = "com.example.banksystem.proto";
option java_outer_classname = "CardProto";

service CardService {
  rpc CreateCard (CreateCardRequest) returns (CardResponse);
  rpc GetCardById (GetCardByIdRequest) returns (CardResponse);
  rpc DeleteCard (DeleteCardRequest) returns (DeleteCardResponse);
  rpc IncreaseCardBalance (IncreaseCardBalanceRequest) returns (CardResponse);
  rpc DecreaseCardBalance (DecreaseCardBalanceRequest) returns (CardResponse);
}
message GetCardByIdRequest{
  int64 id = 1;
}
message CreateCardRequest {
  string cardNumber = 1;
  string expirationDate = 2;
  string cvv = 3;
  string cardHolderName = 4;
  int64 userId = 5;
}

message CardResponse {
  int64 id = 1;
  string cardNumber = 2;
  string expirationDate = 3;
  string cvv = 4;
  string cardHolderName = 5;
  int64 userId = 6;
  int64 cardBalance = 7;
}

message DeleteCardResponse {
  int64 id = 1;
}

message DeleteCardRequest {
  int64 id = 1;
}
message IncreaseCardBalanceRequest {
  int64 id = 1;
  int64 cardNumber = 2;
  double amountToUpdate = 3;
}
message DecreaseCardBalanceRequest {
  int64 id = 1;
  int64 cardNumber = 2;
  double amountToUpdate = 3;
}